# Generated by Django 5.0.2 on 2025-04-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_wallpaper_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='wallpaper',
            options={},
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='razorpay_payment_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='razorpay_signature',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
