# Generated by Django 5.0.2 on 2025-04-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_wallpaper_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='categories',
        ),
    ]
